[tool.cibuildwheel]
build-frontend = "build[uv]"
test-requires = ["pytest>=6", "."]
test-command = """
pytest {project}/tests \
       {package}/tests-cpu-kernels \
       {package}/tests-cpu-kernels-explicit \
       {package}/tests-spec \
       {package}/tests-spec-explicit
"""
skip = [
    "pp*win*",
    "pp*-manylinux_i686",
]
test-skip = [
    "*universal2:arm64",
    "pp*",
    "*musllinux*",
]
build-verbosity = 1

[tool.cibuildwheel.environment]
PIP_ONLY_BINARY = "cmake,numpy"

[[tool.cibuildwheel.overrides]]
select = "cp313*"
environment.PYO3_USE_ABI3_FORWARD_COMPATIBILITY = "1"
