name: Deploy C++

on:
  workflow_dispatch:
    inputs:
        publish-pypi:
            type: boolean
            description: Publish to PyPI

jobs:

  build-wheels:
    uses: ./.github/workflows/build-wheels.yml

  upload-awkward-cpp:
    needs: [build-wheels]
    runs-on: ubuntu-latest
    if: inputs.publish-pypi
    permissions:
      id-token: write
      attestations: write
      contents: read
    environment:
      name: "pypi"
      url: "https://pypi.org/project/awkward-cpp/"
    steps:

    - uses: actions/download-artifact@v4
      with:
        pattern: "awkward-cpp*"
        path: dist
        merge-multiple: true

    - name: List distributions to be deployed
      run: ls -l dist/

    - name: Generate artifact attestation for sdist and wheel
      uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c # v1.4.3
      with:
        subject-path: "dist/awkward*cpp-*"

    - uses: pypa/gh-action-pypi-publish@v1.10.1
